---
- name: launching AWS instance using Ansible
  ec2:
    key_name: "aws_instance_ansible" 
    instance_type: t2.micro
    image: ami-0b614a5d911900a9b
    region: us-east-2
    wait: yes
    group_id: sg-0dab4806186551d5c
    count: 1
    #vpc_subnet_id: subnet-0c8ff53e2f7e49838
    aws_access_key: AKIAY5XZL2MMTKKYZROT
    aws_secret_key: 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
