---
- name: launching AWS instance using Ansible
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    wait: yes
    group_id: "{{ id_group }}"
    count: 1
    #vpc_subnet_id: subnet-0c8ff53e2f7e49838
    aws_access_key: "{{ aws_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
